import type { Metadata } from "next";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { HeaderUser } from "@/components/header-user";
import NextAuthProvider from "@/components/providers/session-provider";

export const metadata: Metadata = {
  title: "Insights",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <NextAuthProvider>
              <header className="flex h-16 shrink-0 items-center justify-between gap-2 border-b bg-background px-4">
                <div className="flex items-center gap-2">
                  <SidebarTrigger className="-ml-1" />
                  <p className="text-[16px] font-medium">Albaly Insights</p>
                </div>
                <div className="flex items-center gap-2">
                  <HeaderUser />
                </div>
              </header>
              <main className="flex-1 p-4 bg-[#FAFAFA] overflow-y-auto">
                {children}
              </main>
            </NextAuthProvider>
          </SidebarInset>
        </SidebarProvider>
  );
}
